import { TrendingUp, Zap, Crown } from 'lucide-react';

export const PLANS = [
  {
    name: 'Free',
    description: 'Discover trending products',
    price: '$0',
    period: '/forever',
    icon: TrendingUp,
    id: 'free',
    features: [
      { text: 'Browse trending products', included: true },
      { text: 'Basic filters & search', included: true },
      { text: 'View velocity scores', included: true },
      { text: '5 product views/day', included: true },
      { text: 'Reddit sentiment preview', included: true },
      { text: 'AI Product Analyzer', included: false },
      { text: 'Historical trend charts', included: false },
      { text: 'Competitor analysis', included: false },
      { text: 'Product comparison', included: false },
    ],
  },
  {
    name: 'Pro',
    description: 'For serious dropshippers',
    price: '$29',
    period: '/month',
    icon: Zap,
    id: 'pro',
    checkoutUrl: 'https://checkout.dodopayments.com/buy/pdt_0NY3IHReMQC9KOCw0JLrM?quantity=1',
    features: [
      { text: 'Everything in Free', included: true },
      { text: 'Unlimited product views', included: true },
      { text: '50 AI analyses/month', included: true },
      { text: 'Full Reddit thread access', included: true },
      { text: 'Historical trend charts', included: true },
      { text: 'Competitor analysis', included: true },
      { text: 'Product comparison (up to 4)', included: true },
      { text: 'Export reports as PDF', included: true },
      { text: 'Email alerts for trends', included: false },
    ],
  },
  {
    name: 'Business',
    description: 'For teams & agencies',
    price: '$99',
    period: '/month',
    icon: Crown,
    id: 'business',
    checkoutUrl: 'https://checkout.dodopayments.com/buy/pdt_0NY3ILPFd7lhczuaQ59Ld?quantity=1',
    features: [
      { text: 'Everything in Pro', included: true },
      { text: 'Unlimited AI analyses', included: true },
      { text: 'Compare up to 10 products', included: true },
      { text: 'API access', included: true },
      { text: 'White-label reports', included: true },
      { text: 'Real-time email alerts', included: true },
      { text: 'Priority support', included: true },
      { text: 'Team collaboration (5 seats)', included: true },
      { text: 'Custom integrations', included: true },
    ],
  },
];
